### ISSUE TITLE
no demultiplexing 

### ISSUE THREAD

**Issue by marwa38** [MW55/Natrix#38]
Hello 

Thanks for the Natrix, the first time to give it a try, hope that it will work fine. I have experience with analyzing data using trim galore and Rstudio for this. 

re the example_data.csv
I don't have a probe as my samples are already demultiplexed so I will leave probe, poly_N, Barcode for both forward and reverse blank in the .csv file. 

while re specific primer in the same .csv file, I have V3-V4 primer sets, are these the ones to be added? or the Illumina primer set? should I include the V3-V4 overhangs in the primer sequence?
To skip this step of demultiplexing or other steps, should I change that in the config file only or other input files should be changed accordingly?

Thanks 
Marwa

**Comment by MW55** [comment]
Hello Marwa,

thank you for your questions!
The "probe" column is if you have multiple samples (i.e. sample1_A_R1.fastq.gz, sample1_A_R2.fastq.gz, sample2_A_R1.fastq.gz, sample2_A_R2.fastq.gz), you write the filenames without the paired-end direction identifier (_R1, _R2) and without the filename extensions in this column (i.e. sample1, sample2) so that Natrix knows which files belong to which primer. Poly_N and barcode can be left blank in the .csv file if your data does not have these.

Regarding the specific primers: You would add any additional subsequences you want to be removed from your data. If your data contains both the Illumina primer and the V3-V4 primer, you would add both. Most of the time, however, the sequencing company already removed the Illumina primer and only the V3-V4 primers are left in the data, so you only have to remove those.

For skipping the demultiplexing, you only have to set demultiplexing to FALSE in the config file. If your data is already assembled, there is also a parameter in the config file to skip the assembly of paired-end reads. 

If you want to skip further steps, you need to adjust your input data accordingly. You can do that by searching for the rule you want to use as a starting point (in the scripts contained in the rule folder) and adjusting your files' path and name according to the input naming convention for your starting rule.

I hope I was able to help you, if you have further questions, feel free to ask!

Best
Marius
